<div dir="rtl" style="text-align: center;">

# لیگ علم داده
### انجمن هوش مصنوعی دانشگاه خوارزمی - کارگروه کاوش عملی
#### هفته اول: ساختن پایه‌ها و درک عمیق داده 
**نام و نام خانوادگی:**  
**سرگروه:**  
**تاریخ ارسال:** 

---

</div>

<div dir="rtl">

### 📥 فراخوانی کتابخانه‌ها
در این سلول تمام کتابخانه‌های مورد نیاز (Pandas, NumPy, Matplotlib, Scipy و ...) را ایمپورت کنید.

</div>

In [1]:
# Import libraries here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
...

%matplotlib inline

<div dir="rtl">

---
## چالش ۱: اولین برخورد (First Contact)

</div>

In [2]:
# Load datasets
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

print("Train shape:", train_data.shape)
print("Test shape:", test_data.shape)
# Display the first few rows to verify loading
train_data.head(10)

# TODO: Write your code here

Train shape: (359, 33)
Test shape: (36, 32)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,LE3,A,4,4,health,other,...,4,2,4,1,1,4,14,12,10,11
1,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,4,8,9,10
2,GP,M,19,U,GT3,T,3,3,other,other,...,4,4,4,1,1,3,20,15,14,13
3,GP,F,16,U,GT3,T,3,3,other,services,...,4,3,3,2,4,5,54,11,12,11
4,GP,F,17,U,GT3,T,3,2,other,other,...,4,3,2,2,3,2,0,7,8,0
5,GP,F,18,U,LE3,T,4,3,other,other,...,4,4,5,1,2,2,10,10,8,8
6,GP,F,15,U,GT3,T,3,2,services,other,...,4,3,5,1,1,2,26,7,6,6
7,GP,M,17,R,LE3,T,1,2,other,other,...,2,2,2,3,3,5,8,16,12,13
8,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
9,GP,F,15,U,GT3,A,4,3,services,services,...,4,3,2,1,1,1,0,14,15,15

In [5]:
# test_data.head()

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      359 non-null    object
 1   sex         359 non-null    object
 2   age         359 non-null    int64
 3   address     359 non-null    object
 4   famsize     359 non-null    object
 5   Pstatus     359 non-null    object
 6   Medu        359 non-null    int64
 7   Fedu        359 non-null    int64
 8   Mjob        359 non-null    object
 9   Fjob        359 non-null    object
 10  reason      359 non-null    object
 11  guardian    359 non-null    object
 12  traveltime  359 non-null    int64
 13  studytime   359 non-null    int64
 14  failures    359 non-null    int64
 15  schoolsup   359 non-null    object
 16  famsup      359 non-null    object
 17  paid        359 non-null    object
 18  activities  359 non-null    object
 19  nursery     359 non-null    object
 20  higher      359 non-null    object
 21  internet    359 non-null    object
 22  romantic    359 non-null    object
 23  famrel      359 non-null    int64
 24  freetime    359 non-null    int64
 25  goout       359 non-null    int64
 26  Dalc        359 non-null    int64
 27  Walc        359 non-null    int64
 28  health      359 non-null    int64
 29  absences    359 non-null    int64
 30  G1          359 non-null    int64
 31  G2          359 non-null    int64
 32  G3          359 non-null    int64
dtypes: int64(16), object(17)
memory usage: 92.7+ KB

In [19]:
for i in train_data.columns:
    print(train_data.value_counts(i))
    print()

school
GP    316
MS     43
Name: count, dtype: int64

sex
F    190
M    169
Name: count, dtype: int64

age
16    97
17    93
18    72
15    68
19    24
20     3
21     1
22     1
Name: count, dtype: int64

address
U    277
R     82
Name: count, dtype: int64

famsize
GT3    257
LE3    102
Name: count, dtype: int64

Pstatus
T    322
A     37
Name: count, dtype: int64

Medu
4    120
2     92
3     90
1     54
0      3
Name: count, dtype: int64

Fedu
2    105
3     91
4     86
1     75
0      2
Name: count, dtype: int64

Mjob
other       133
services     92
at_home      53
teacher      52
health       29
Name: count, dtype: int64

Fjob
other       203
services     96
teacher      26
at_home      18
health       16
Name: count, dtype: int64

reason
course        130
home          102
reputation     94
other          33
Name: count, dtype: int64

guardian
mother    247
father     81
other      31
Name: count, dtype: int64

traveltime
1    232
2    100
3     21
4      6
Name: count, dtype: int64

studytime
2    181
1     96
3     59
4     23
Name: count, dtype: int64

failures
0    282
1     48
2     15
3     14
Name: count, dtype: int64

schoolsup
no     311
yes     48
Name: count, dtype: int64

famsup
yes    221
no     138
Name: count, dtype: int64

paid
no     194
yes    165
Name: count, dtype: int64

activities
yes    183
no     176
Name: count, dtype: int64

nursery
yes    283
no      76
Name: count, dtype: int64

higher
yes    340
no      19
Name: count, dtype: int64

internet
yes    295
no      64
Name: count, dtype: int64

romantic
no     236
yes    123
Name: count, dtype: int64

famrel
4    175
5     95
3     64
2     18
1      7
Name: count, dtype: int64

freetime
3    142
4    106
2     57
5     35
1     19
Name: count, dtype: int64

goout
3    119
2     92
4     80
5     48
1     20
Name: count, dtype: int64

Dalc
1    253
2     69
3     22
5      8
4      7
Name: count, dtype: int64

Walc
1    138
3     77
2     75
4     45
5     24
Name: count, dtype: int64

health
5    131
3     81
4     63
1     42
2     42
Name: count, dtype: int64

absences
0     100
2      57
4      50
6      30
8      20
10     15
14     11
12     11
3       8
7       7
16      7
18      5
20      4
5       4
1       3
11      3
15      3
9       3
22      3
13      1
17      1
19      1
21      1
23      1
24      1
25      1
26      1
28      1
30      1
38      1
40      1
54      1
56      1
75      1
Name: count, dtype: int64

G1
10    46
8     38
11    37
7     33
13    31
12    31
14    30
9     27
6     23
15    23
16    18
5      7
18     6
17     6
3      1
4      1
19     1
Name: count, dtype: int64

G2
9     44
10    42
12    37
13    35
11    35
15    31
8     28
14    23
7     18
5     15
6     14
0     11
16    11
18     9
17     3
19     2
4      1
Name: count, dtype: int64

G3
10    50
11    45
0     35
13    29
12    29
15    29
14    27
8     26
9     25
16    15
6     14
7      9
18     9
5      7
17     5
19     4
4      1
Name: count, dtype: int64

In [4]:
train_data.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000
mean,16.735376,2.752089,2.512535,1.445682,2.025070,0.334262,3.927577,3.225627,3.122563,1.462396,2.281337,3.554318,5.927577,10.813370,10.660167,10.348189
std,1.272683,1.099690,1.087889,0.682361,0.830249,0.735927,0.903310,1.003798,1.106869,0.870437,1.275669,1.384966,8.246909,3.244461,3.668734,4.535852
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,13.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,19.000000

<div dir="rtl" style="text-align: justify;">

### 📝 تحلیل شما (پاسخ تشریحی):

#### ۱. معنای ستون‌های ویژگی (Attributes):

**الف) اطلاعات فردی و خانوادگی:**
* `school`: نام مدرسه (**GP**: گابریل پریرا، **MS**: موسینیو).
* `sex`: جنسیت (**F**: دختر، **M**: پسر).
* `age`: سن دانش‌آموز (از ۱۵ تا ۲۲ سال).
* `address`: نوع محل سکونت (**U**: شهری/Urban، **R**: روستایی/Rural).
* `famsize`: اندازه خانوار (**LE3**: ۳ نفر یا کمتر، **GT3**: بیشتر از ۳ نفر).
* `Pstatus`: وضعیت زندگی والدین (**T**: با هم زندگی می‌کنند، **A**: جدا زندگی می‌کنند).
* `Medu` / `Fedu`: سطح تحصیلات مادر/پدر (۰: بی‌سواد، ۱: ابتدایی، ۲: راهنمایی، ۳: دبیرستان، **۴: تحصیلات عالی**).
* `Mjob` / `Fjob`: شغل مادر/پدر (**teacher**: معلم، **health**: کادر درمان، **services**: خدمات دولتی/اداری، **at_home**: خانه‌دار، **other**: سایر).
* `guardian`: قیم یا سرپرست قانونی (**mother**، **father**، **other**).

**ب) اطلاعات تحصیلی:**
* `reason`: دلیل اصلی انتخاب این مدرسه:
    * **home**: نزدیکی به خانه.
    * **reputation**: اعتبار و شهرت مدرسه.
    * **course**: ترجیح رشته تحصیلی.
    * **other**: سایر دلایل.
* `traveltime`: زمان سفر از خانه به مدرسه (۱: کمتر از ۱۵ دقیقه ... تا ... ۴: بیشتر از ۱ ساعت).
* `studytime`: زمان مطالعه هفتگی (۱: کمتر از ۲ ساعت ... تا ... ۴: بیشتر از ۱۰ ساعت).
* `failures`: تعداد دفعات مردودی در کلاس‌های گذشته (بیشتر از 4 دفعه، با همان 4 نشان داده می‌شود).
* `schoolsup`: دریافت حمایت آموزشی (کلاس تقویتی) از مدرسه (**yes/no**).
* `famsup`: دریافت حمایت آموزشی از خانواده (**yes/no**).
* `paid`: کلاس‌های خصوصی پولی برای دروس (**yes/no**).
* `activities`: شرکت در فعالیت‌های فوق‌برنامه (**yes/no**).
* `nursery`: سابقه رفتن به مهدکودک (**yes/no**).
* `higher`: تمایل به ادامه تحصیل در دانشگاه (**yes/no**).
* `internet`: دسترسی به اینترنت در خانه (**yes/no**).
* `absences`: تعداد جلسات غیبت در مدرسه (عدد، مثلاً ۰ تا ۷۵).

**ج) سبک زندگی (مقیاس‌های ۱ تا ۵):**
*(در این ستون‌ها عدد ۱ به معنی کمترین/بدترین و عدد ۵ به معنی بیشترین/بهترین وضعیت است)*
* `romantic`: داشتن رابطه عاطفی (**yes/no**).
* `famrel`: کیفیت روابط خانوادگی (۱: بسیار بد ... **۵: عالی**).
* `freetime`: میزان وقت آزاد بعد از مدرسه (۱: بسیار کم ... **۵: بسیار زیاد**).
* `goout`: میزان بیرون رفتن با دوستان (۱: بسیار کم ... **۵: بسیار زیاد**).
* `Dalc`: مصرف الکل در روزهای کاری هفته (۱: بسیار کم ... **۵: بسیار زیاد**).
* `Walc`: مصرف الکل در آخر هفته‌ها (۱: بسیار کم ... **۵: بسیار زیاد**).
* `health`: وضعیت سلامت فعلی (۱: بسیار بد ... **۵: بسیار خوب**).

**د) نمرات (متغیرهای هدف):**
* `G1`: نمره دوره اول (بین ۰ تا ۲۰).
* `G2`: نمره دوره دوم (بین ۰ تا ۲۰).
* `G3`: **نمره نهایی** (Target Variable - بین ۰ تا ۲۰).


#### ۲. دسته‌بندی ستون‌ها (Numerical vs Categorical):
با توجه به خروجی `info` و مقادیر ستون‌ها:

* **ستون‌های دسته‌ای (Categorical):**
    این ستون‌ها بیانگر گروه‌ها یا وضعیت‌های کیفی هستند:
    > `school`, `sex`, `address`, `famsize`, `Pstatus`, `Mjob`, `Fjob`, `reason`, `guardian`, `schoolsup`, `famsup`, `paid`, `activities`, `nursery`, `higher`, `internet`, `romantic`

* **ستون‌های عددی (Numerical):**
    شامل اعداد پیوسته یا رتبه‌ای (Ordinal) هستند:
    > `age`, `absences`, `G1`, `G2`, `G3` (پیوسته/گسسته شمارشی)
    > `Medu`, `Fedu`, `traveltime`, `studytime`, `failures`, `famrel`, `freetime`, `goout`, `Dalc`, `Walc`, `health` (رتبه‌ای/Ordinal)

#### ۳. مشاهدات اولیه و درک داده‌ها (Data Understanding):
با بررسی خروجی‌های `describe` و `value_counts` نکات زیر قابل توجه است:

1.  **عدم وجود داده گمشده:** تعداد ردیف‌ها ۳۵۹ است و تمام ستون‌ها ۳۵۹ مقدار `non-null` دارند. پس در نگاه اول داده‌های `NaN` نداریم (مگر اینکه با فرمت دیگری مثل ؟ یا ۰ پنهان شده باشند).
2.  **توزیع نامتوازن مدارس:** اکثر داده‌ها مربوط به مدرسه `GP` (۳۱۶ نفر) است و مدرسه `MS` سهم کمی (۴۳ نفر) دارد.
3.  **داده‌های پرت احتمالی (Outliers):** در ستون `absences` میانگین حدود ۶ است، اما مقدار ماکزیمم **۷۵** ثبت شده که بسیار فاصله دارد و مشکوک به داده پرت است.
4.  **بازه نمرات:** نمره نهایی (`G3`) بین ۰ تا ۱۹ تغییر می‌کند (مینیمم ۰ قابل توجه است).
5.  **مصرف الکل:** میانگین مصرف الکل در روزهای کاری (`Dalc`) بسیار پایین (حدود ۱.۴) است، اما در آخر هفته‌ها (`Walc`) افزایش می‌یابد.

</div>

<div dir="rtl">

---
## چالش ۲: معمای ماشین زمان (Data Leakage)

</div>

<div dir="rtl">

#### 📝 پاسخ تشریحی:
[اینجا بنویسید]

</div>

<div dir="rtl">

---
## چالش ۳: شرط‌بندی روی ثبات (Variance & Std)

</div>

In [6]:
# Calculate Variance/Std for each school
# TODO: Write your code here

In [7]:
# Draw Boxplot
# TODO: Write your code here

<div dir="rtl">

#### 📝 تحلیل شما:
[اینجا بنویسید]

</div>

<div dir="rtl">

---
## چالش ۴: راز صفرها (Distributions & Outliers)

</div>

In [8]:
# Plot Histogram
# TODO: Write your code here

In [9]:
# Investigate students with 0 grades
# TODO: Write your code here

<div dir="rtl">

#### 📝 تحلیل شما:
[اینجا بنویسید]

</div>

<div dir="rtl">

---
## چالش ۵: جنگ آمارها (Correlation & Hypothesis)

</div>

In [10]:
# Correlation Matrix Heatmap
# TODO: Write your code here

In [11]:
# T-Test Calculation (P-value)
# TODO: Write your code here

<div dir="rtl">

#### 📝 تحلیل شما (پاسخ به مدیر مالی):
[اینجا بنویسید]

</div>

<div dir="rtl">

---
## چالش ۶: زبان مشترک با کامپیوتر (Encoding)

</div>

In [12]:
# One-Hot Encoding implementation
# TODO: Write your code here

<div dir="rtl">

#### 📝 پاسخ تشریحی:
[اینجا بنویسید]

</div>

<div dir="rtl">

---
## ⛔ تمرین نهایی: شکار باگ (Bug Hunt)

</div>

In [ ]:
# Corrected Code Implementation
# TODO: Write the fixed version here